### ISSUE TITLE
Change Query Chunking to use python libraries instead of gnu commands

### ISSUE THREAD

**Issue by KyleEvers** [cisagov/cyhy-feeds#9]
In PR #8 sed, awk, and mv are used to remove extra characters generated by pulling large queries out in chunks. These sed and awk commands should be replaced with python regexs to increase portability. The mv should be replaced with shutil. See Shane's comments in #8 for more information.

**Comment by mcdonnnj** [comment]
This issue was resolved as part of #29 when document processing was modified. The same shell calls were causing the script to fail bandit pre-commit checks.
